resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 50
    instances:
      items:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      items:
        baseConfig: default



