resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 50
    instances:
      products:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      products:
        baseConfig: default



spring:
  cloud:
    gateway:
      routes:
      - id: msvc-users
        uri: lb://msvc-users
        predicates:
        - Path=/api/users/**
        filters:
        - StripPrefix=2
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        #- Header=X-Request-Id, \d+
        #- Method=GET, POST
        #- Query=name, \d+
        #- Cookie=JSESSIONID, \d+
        filters:
        - name: CircuitBreaker
          args:
            name: products
            statusCodes: 500
            fallbackUri: forward:/api/items/5
        - StripPrefix=2
        - name: SampleCookie
          args:
            message: Adding a cookie to the response
            name: myValue
            value: myValue
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=X-Request-Foo, Bar
        - AddResponseHeader=X-Response-Foo, Bar
        - AddRequestParameter=name, Alex
        - SetResponseHeader=Content-Type, application/json